export const SET_FACTORS = "SET_FACTORS";
export const SET_DARKMODE = "SET_DARKMODE";
export const SET_ONBOARDING = "SET_ONBOARDING";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const SET_REMINDER_TIME = "SET_REMINDER_TIME";
